### PR TITLE
symbol from ES6.

### PR DESCRIPTION
**Pull request by hemanth**
It's a new primitive.

### CODE REVIEW

**Comment by hemanth** [comment]
//cc @jonschlinkert  :cat:

**Comment by jonschlinkert** [comment]
sorry, I've had the flu. I didn't forget

**Comment by hemanth** [comment]
@jonschlinkert Get well soon! Take Care.

**Comment by jonschlinkert** [comment]
sorry for the delay, published to npm

**Comment by hemanth** [comment]
NP. Thank you.

**Pull request merged**
